encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/", views.index, name="wiki"),
    path("wiki/<str:title>", views.entry_page, name="entry_page"),
    path("wiki/<str:title>", views.entry_page, name="link"),
    path("random/", views.random_page, name="random"),
    path("search/",views.search, name="search"),

    path("new_page/", views.new_page, name="new_page"),
    path("edit/<str:title>", views.edit_page, name="edit"),

    # the directory where the file is configured in views.py
]


''' 
need to create this file in each app
if "" in first argument points to root


'''

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponse
from django.shortcuts import render

from . import util

from random import choice

from . import md_converter


from django import forms
#from django.http import HttpResponseRedirect
#from django.urls import reverse

class NewPage(forms.Form):
    title = forms.CharField (widget=forms.TextInput (attrs={'placeholder':'Enter title'}))
    content = forms.CharField (widget=forms.Textarea (attrs={'placeholder':'Enter content here\nAs markdown reference:\n#Heading\n**Bold**'}))

class EditForm(forms.Form):
    content = forms.CharField (widget=forms.Textarea)

class SearchForm(forms.Form):
    search = forms.CharField(label="Search",required= False, widget= forms.TextInput (attrs={'placeholder':'Search Encyclopedia'}))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

'''def wiki(request, name):
    return render(request, "encyclopedia/wiki.html", {
        "name": name.capitalize()
    })'''


'''
def entry_page(request, title):
    return render(request, "encyclopedia/wiki.html",
    {"title": util.get_entry(title)})
    '''

def entry_page(request, title):
    entry_md=util.get_entry(title)
    html = md_converter.to_html(entry_md)
    print(html)
    return render(request, "encyclopedia/wiki.html",{"title": title, "content": html})

'''
TypeError at /wiki/css
get_entry() missing 1 required positional argument: 'title

needed to add the word title inside()
'''

def random_page(request):
    return entry_page(request,choice( util.list_entries()))

def new_page(request):
    if request.method== "POST":
    # si existe post
        form = NewPage(request.POST)
        # tomar la info y guardar en fomulario
        if form.is_valid():
        # controlo si el formulario esta bien (server-side)
            title = form.cleaned_data["title"]
            # separo cada variable del formulario
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return entry_page(request, title)
            #return render(request, "encyclopedia/wiki.html", {"title": util.get_entry(title)})
        else:
           # return entry_page(request( util.save_entry(title, content)))
           # muestro el formulario con los campos completado
            return render(request, "encyclopedia/new_page.html", {"form": form
            })
    else:
        # si no existe post muestro el formulario vacio
        return render(request, "encyclopedia/new_page.html", {"form": NewPage()
        })
    

'''def edit_page(request, title):
    if request.method== "POST":
        edit = EditForm(request.POST)
        if edit.is_valid():
            title = edit.cleaned_data["title"]
            content = edit.cleaned_data["content"]
            #return render(request, "encyclopedia/new_page.html", {"form": form})
            util.save_entry(title, content)
    else:
        #return render(request, "encyclopedia/new_page.html", {"form": NewPage()})
        edit = EditForm({"title": title, "content": util.get_entry(title)})
        return render(request, "encyclopedia/edit.html", {"form": edit, "edit": edit})'''
    

'''def search(request,title):
    #search = SearchForm(request.POST or None)      
    #if request.method == "POST" and search.is_valid():
    if request.method == "POST":
        search = SearchForm(request.POST)
        if search.is_valid():
            search = search.cleaned_data["search"]
            #entries = util.list_entries()
            entry = util.get_entry(title)
        else:
            if search in entry:
                return render(request, "encyclopedia/wiki.html",{"search":search})
    else:
        #return HttpResponseRedirect("wiki:index")
        return render(request, "encyclopedia/wiki.html",{"search":SearchForm()})'''
    
    

'''def search_entry(search):
    """
    Retrieves a filtered list of encyclopedia entries.
    """
    return list(filter(lambda x: search.upper() in x.upper(), list_entries()))'''


def search(request):
    entries = []
    if request.method == "POST":
        search = SearchForm(request.POST)
        if search.is_valid():
            search = search.cleaned_data["search"]
            entries = list(filter(lambda x: search.upper() in x.upper(), util.list_entries()))
            if(len(entries) == 1):
                return entry_page(request, entries[0])
    return render(request, "encyclopedia/searchlist.html",{"entries": entries})
    


'''def search(request):
    #search = SearchForm(request.POST or None)      
    #if request.method == "POST" and search.is_valid():
    if request.method == "POST":
        search = SearchForm(request.POST)
        if search.is_valid():
            search = search.cleaned_data["search"]
            return render(request, "encyclopedia/wiki.html",{"search":search})
    else:
        return render(request, "encyclopedia/wiki.html",{"search":SearchForm()})'''



'''def new_page(request):
    if request.method== "POST":
        form = NewPage(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if title == util.get_entry(title):
                print("An entry named:{title} already exists")
            

            else:
                util.save_entry(title, content)
                #return HttpResponseRedirect(reverse("wiki:wiki"))
                return entry_page(request, title)
                #return render(request, "encyclopedia/wiki.html", {"title": util.get_entry(title)})

        else:
           # return entry_page(request( util.save_entry(title, content)))
           #print("An entry named:{title} already exists")
            return render(request, "encyclopedia/new_page.html", {"form": form
            })
    else:
        return render(request, "encyclopedia/new_page.html", {"form": NewPage()
        })'''


            
'''return render(request, "encyclopedia/wiki.html",
    {"title": util.get_entry(title)})'''



'''def edit_page(request, title):
    if request.method== "POST":
        edit = EditForm(request.POST)
        if edit.is_valid():
            title = edit.cleaned_data["title"]
            content = edit.cleaned_data["content"]
            #return render(request, "encyclopedia/new_page.html", {"form": form})
            util.save_entry(title, content)
    else:
        #return render(request, "encyclopedia/new_page.html", {"form": NewPage()})
        edit = EditForm({"title": title, "content": util.get_entry(title)})
        return render(request, "encyclopedia/edit.html", {"form": edit, "edit": edit})'''

def edit_page(request, title):
    if request.method== "POST":
        edit = EditForm(request.POST)
        if edit.is_valid():
            content = edit.cleaned_data["content"]
            util.save_entry(title, content)
            return entry_page(request, title)
    else:
        edit = EditForm({"content": util.get_entry(title)})
        return render(request, "encyclopedia/edit_page.html", {"form": edit, "title": title})

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<h1>Edit entry: {{title}}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="SAVE">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <!--<li><a href="{% url 'wiki:index' %}">{{ entry }}</a></li>-->
            <li><a href= "{% url 'wiki:link' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="post">
                    {% csrf_token %}                  
                    <input type="text" name="search" placeholder="Search Encyclopedia" id="id_search">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_page' %}">New Entry</a>
                </div>
                <div>
                    <a class="nav-link"  href = "{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<h1>New entry</h1>
    <form action="{% url 'wiki:new_page' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="SAVE">
    </form>
    <!--<a href="{% url 'wiki:index' %}">View entries</a>-->
{% endblock %}

encyclopedia/templates/encyclopedia/searchlist.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search results...</h1>

    <ul>
        {% for entry in entries %}
            <!--<li><a href="{% url 'wiki:index' %}">{{ entry }}</a></li>-->
            <li><a href= "{% url 'wiki:link' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
        {% if not entries %}
            <p>There were no results matching the query.</p>
        {% endif %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {% if content %}
            <div>
                {{ content|safe }}
            </div>        
            <div>
                <a href="{% url 'wiki:edit' title=title %}">Edit entry</a>
            </div>
        {% else %}
            <p>Wikipedia does not have an article with this exact name.</p>
        {% endif %}
{% endblock %}